### ISSUE TITLE
promu build does not work on SmartOS

### ISSUE THREAD

**Issue by robinbowes** [prometheus/promu#52]
I'm trying to build node_exporter on SmartOS, but get this error when I run make:

```
[root@build01 ~/software/go/src/github.com/prometheus/node_exporter]# make
>> formatting code
cmd/go: unsupported GOOS/GOARCH pair sunos/i86pc
Makefile:55: recipe for target 'promu' failed
make: *** [promu] Error 2
```

Any chance of this working on SmartOS?

**Comment by lastsky** [comment]
check Joyent's way it should work:

https://speakerdeck.com/tgross/triton# 

other links here (full conference):
https://github.com/promcon/slides-2016/blob/master/README.md

this task probably should be closed.

**Comment by robinbowes** [comment]
I'm not sure how those links answer my question?

**Comment by lastsky** [comment]
hope you may find answers how to monitor smartos and send native metrics to prometheus with another way without dependency from Golang and node_exporter.

**Comment by robinbowes** [comment]
Ah, OK. I suspect that stuff will be Triton-only. Maybe I'll have to switch to Triton.

**Comment by lastsky** [comment]
probably you may check this doc and use bare JS fork for hypervisor: https://github.com/joyent/triton-cmon/blob/master/docs/README.md#example

~~~
GET https://<container_uuid>.cmon.<az>.triton.zone:9163/metrics
---
# HELP cpu_user_usage User CPU utilization in nanoseconds
# TYPE cpu_user_usage counter
cpu_user_usage 63967515436752
# HELP cpu_sys_usage System CPU usage in nanoseconds
# TYPE cpu_sys_usage counter
cpu_sys_usage 1162987685940
# HELP cpu_wait_time CPU wait time in nanoseconds
# TYPE cpu_wait_time counter
cpu_wait_time 45927954147062
~~~

I have the same problem and I gonna test it soon.

**Comment by liuzhen** [comment]
any update on the original issue?

**Comment by sdurrheimer** [comment]
Unfortunately, I have no way or experience nor the time to test this on SmartOS. Any help would be appreciated.

**Comment by robinbowes** [comment]
I've re-visited this, and the build is getting further, but throwing a different error:
```
[root@build01 ~/software/go/src/github.com/prometheus/node_exporter]# make
>> formatting code
>> vetting code
>> running staticcheck
/root/software/go/src/github.com/prometheus/node_exporter/collector/meminfo.go:44:18: invalid operation: c (variable of type *meminfoCollector) has no field or method getMemInfo
/root/software/go/src/github.com/prometheus/node_exporter/collector/meminfo.go:49:20: cannot range over memInfo (invalid operand)
couldn't load packages due to errors: github.com/prometheus/node_exporter/collector
Makefile:68: recipe for target 'staticcheck' failed
make: *** [staticcheck] Error 1
```

**Comment by robinbowes** [comment]
See also: https://github.com/prometheus/node_exporter/issues/596

**Comment by grobie** [comment]
The error above is unrelated to promu and a node_exporter issue.

**Comment by robinbowes** [comment]
Well, that's progress, I guess :)

**Comment by lastsky** [comment]
but solaris is not linux

https://www.claudiokuenzler.com/blog/434/get-real-memory-usage-statistics-physical-smartos-global#.WXEBRNOGNE4

**Comment by lastsky** [comment]
note: The **pain** to get real memory usage stats on physical SmartOS

**Comment by robinbowes** [comment]
https://github.com/prometheus/node_exporter/pull/620 fixes that build.

I now have this error:
```
[root@build01 ~/software/go/src/github.com/prometheus/node_exporter]# make
>> formatting code
>> vetting code
>> running staticcheck
package github.com/prometheus/promu/vendor/gopkg.in/fsnotify.v1: no buildable Go source files in /root/software/go/src/github.com/prometheus/promu/vendor/gopkg.in/fsnotify.v1
Makefile:88: recipe for target '/root/software/go/bin/promu' failed
make: *** [/root/software/go/bin/promu] Error 1
```

**Comment by sdurrheimer** [comment]
Should be fixed by #76.

**Comment by mguegan** [comment]
Hi,
I still have some issue when trying to build node_exporter : 
```[root@pkgbuild-16-4 ~/work/src/github.com/prometheus/node_exporter]# make
>> formatting code
>> vetting code
>> running staticcheck
>> building binaries
 >   node_exporter
# github.com/prometheus/node_exporter
/opt/local/go/pkg/tool/solaris_amd64/link: running gcc failed: exit status 1
ld: fatal: library -lsocket: not found
ld: fatal: library -lnsl: not found
ld: fatal: library -lsendfile: not found
ld: fatal: library -lc: not found
ld: fatal: file processing errors. No output written to $WORK/github.com/prometheus/node_exporter/_obj/exe/a.out
collect2: error: ld returned 1 exit status

!! command failed: build -o /root/work/src/github.com/prometheus/node_exporter/node_exporter -ldflags -X github.com/prometheus/node_exporter/vendor/github.com/prometheus/common/version.Version=0.14.0 -X github.com/prometheus/node_exporter/vendor/github.com/prometheus/common/version.Revision=a47f033f1ba17b67094ec7e0900a639824151dce -X github.com/prometheus/node_exporter/vendor/github.com/prometheus/common/version.Branch=master -X github.com/prometheus/node_exporter/vendor/github.com/prometheus/common/version.BuildUser=root@pkgbuild-16-4.virtua.ch -X github.com/prometheus/node_exporter/vendor/github.com/prometheus/common/version.BuildDate=20171004-14:48:38  -extldflags '-static' -a -tags 'netgo static_build' github.com/prometheus/node_exporter: exit status 2
Makefile:99: recipe for target 'build' failed
make: *** [build] Error 1```
